modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
modId="torchbowmod"
version="1.0"
displayName="TorchBowMod"
updateJSONURL="https://raw.githubusercontent.com/noriokun4649/TorchBowMod/master/update.json"
credits="noriokun4649"
authors="noriokun4649"
description="Adds a TorchBow."

[[dependencies.torchbowmod]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchbowmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"